//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/Client/Input/BattleInput.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @BattleInput : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @BattleInput()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""BattleInput"",
    ""maps"": [
        {
            ""name"": ""BattleCommands"",
            ""id"": ""d4de80e3-8b1a-4319-89a6-3e267139ae86"",
            ""actions"": [
                {
                    ""name"": ""Move 1"",
                    ""type"": ""Button"",
                    ""id"": ""5eea8914-ae2a-4c33-97c4-70c39eafb1f2"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Move 2"",
                    ""type"": ""Button"",
                    ""id"": ""6f7394eb-1951-4ea9-971f-01cc061968c4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Move 3"",
                    ""type"": ""Button"",
                    ""id"": ""d56b9372-fb32-407e-882b-5f992263513b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Move 4"",
                    ""type"": ""Button"",
                    ""id"": ""78fb0e8c-7a81-47e0-b627-14db32821904"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Switch 1"",
                    ""type"": ""Button"",
                    ""id"": ""482a21b7-ea0b-43bf-b558-a04fe1c83ed6"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Switch 2"",
                    ""type"": ""Button"",
                    ""id"": ""0c9e1f39-2ed6-4205-9059-0e375ccb9b2e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Switch 3"",
                    ""type"": ""Button"",
                    ""id"": ""73e30338-60bc-46f7-8ad9-7b155ffb3846"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Switch 4"",
                    ""type"": ""Button"",
                    ""id"": ""5ae0c7cb-1d18-412f-885f-9ab6f7a2f697"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Switch 5"",
                    ""type"": ""Button"",
                    ""id"": ""0457713b-b9bd-422c-ac53-b9259d59c66a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Switch 6"",
                    ""type"": ""Button"",
                    ""id"": ""9f7c7002-e4c6-4f02-8953-62a628ecb715"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""397c00a7-52dc-45ff-a375-a6bfcac3408b"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move 1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5ed70ef3-f068-4783-8fd7-d3cb440ccb2a"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move 2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""904f237a-f155-4162-9dd7-599ff14d8c4a"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move 3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d6b733a2-69c1-4a64-9f98-cd53cdc50856"",
                    ""path"": ""<Keyboard>/4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move 4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1fab0c2e-0015-4c2e-86b7-af4e8fac3e5e"",
                    ""path"": ""<Keyboard>/f1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Switch 1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6e7d0c14-f86e-42f1-b0c8-7993c8113578"",
                    ""path"": ""<Keyboard>/f2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Switch 2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2526acc8-c7d5-4b0b-8f1f-caaf880cacaf"",
                    ""path"": ""<Keyboard>/f3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Switch 3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""be9617e1-d7ef-4e99-bc06-79cf02a5ebbd"",
                    ""path"": ""<Keyboard>/f4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Switch 4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8d50296f-86e0-41ff-862f-0b77896e80d2"",
                    ""path"": ""<Keyboard>/f5"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Switch 5"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f8acb16f-8b31-4cc0-8473-bc1d2110deb2"",
                    ""path"": ""<Keyboard>/f6"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Switch 6"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // BattleCommands
        m_BattleCommands = asset.FindActionMap("BattleCommands", throwIfNotFound: true);
        m_BattleCommands_Move1 = m_BattleCommands.FindAction("Move 1", throwIfNotFound: true);
        m_BattleCommands_Move2 = m_BattleCommands.FindAction("Move 2", throwIfNotFound: true);
        m_BattleCommands_Move3 = m_BattleCommands.FindAction("Move 3", throwIfNotFound: true);
        m_BattleCommands_Move4 = m_BattleCommands.FindAction("Move 4", throwIfNotFound: true);
        m_BattleCommands_Switch1 = m_BattleCommands.FindAction("Switch 1", throwIfNotFound: true);
        m_BattleCommands_Switch2 = m_BattleCommands.FindAction("Switch 2", throwIfNotFound: true);
        m_BattleCommands_Switch3 = m_BattleCommands.FindAction("Switch 3", throwIfNotFound: true);
        m_BattleCommands_Switch4 = m_BattleCommands.FindAction("Switch 4", throwIfNotFound: true);
        m_BattleCommands_Switch5 = m_BattleCommands.FindAction("Switch 5", throwIfNotFound: true);
        m_BattleCommands_Switch6 = m_BattleCommands.FindAction("Switch 6", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // BattleCommands
    private readonly InputActionMap m_BattleCommands;
    private IBattleCommandsActions m_BattleCommandsActionsCallbackInterface;
    private readonly InputAction m_BattleCommands_Move1;
    private readonly InputAction m_BattleCommands_Move2;
    private readonly InputAction m_BattleCommands_Move3;
    private readonly InputAction m_BattleCommands_Move4;
    private readonly InputAction m_BattleCommands_Switch1;
    private readonly InputAction m_BattleCommands_Switch2;
    private readonly InputAction m_BattleCommands_Switch3;
    private readonly InputAction m_BattleCommands_Switch4;
    private readonly InputAction m_BattleCommands_Switch5;
    private readonly InputAction m_BattleCommands_Switch6;
    public struct BattleCommandsActions
    {
        private @BattleInput m_Wrapper;
        public BattleCommandsActions(@BattleInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @Move1 => m_Wrapper.m_BattleCommands_Move1;
        public InputAction @Move2 => m_Wrapper.m_BattleCommands_Move2;
        public InputAction @Move3 => m_Wrapper.m_BattleCommands_Move3;
        public InputAction @Move4 => m_Wrapper.m_BattleCommands_Move4;
        public InputAction @Switch1 => m_Wrapper.m_BattleCommands_Switch1;
        public InputAction @Switch2 => m_Wrapper.m_BattleCommands_Switch2;
        public InputAction @Switch3 => m_Wrapper.m_BattleCommands_Switch3;
        public InputAction @Switch4 => m_Wrapper.m_BattleCommands_Switch4;
        public InputAction @Switch5 => m_Wrapper.m_BattleCommands_Switch5;
        public InputAction @Switch6 => m_Wrapper.m_BattleCommands_Switch6;
        public InputActionMap Get() { return m_Wrapper.m_BattleCommands; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(BattleCommandsActions set) { return set.Get(); }
        public void SetCallbacks(IBattleCommandsActions instance)
        {
            if (m_Wrapper.m_BattleCommandsActionsCallbackInterface != null)
            {
                @Move1.started -= m_Wrapper.m_BattleCommandsActionsCallbackInterface.OnMove1;
                @Move1.performed -= m_Wrapper.m_BattleCommandsActionsCallbackInterface.OnMove1;
                @Move1.canceled -= m_Wrapper.m_BattleCommandsActionsCallbackInterface.OnMove1;
                @Move2.started -= m_Wrapper.m_BattleCommandsActionsCallbackInterface.OnMove2;
                @Move2.performed -= m_Wrapper.m_BattleCommandsActionsCallbackInterface.OnMove2;
                @Move2.canceled -= m_Wrapper.m_BattleCommandsActionsCallbackInterface.OnMove2;
                @Move3.started -= m_Wrapper.m_BattleCommandsActionsCallbackInterface.OnMove3;
                @Move3.performed -= m_Wrapper.m_BattleCommandsActionsCallbackInterface.OnMove3;
                @Move3.canceled -= m_Wrapper.m_BattleCommandsActionsCallbackInterface.OnMove3;
                @Move4.started -= m_Wrapper.m_BattleCommandsActionsCallbackInterface.OnMove4;
                @Move4.performed -= m_Wrapper.m_BattleCommandsActionsCallbackInterface.OnMove4;
                @Move4.canceled -= m_Wrapper.m_BattleCommandsActionsCallbackInterface.OnMove4;
                @Switch1.started -= m_Wrapper.m_BattleCommandsActionsCallbackInterface.OnSwitch1;
                @Switch1.performed -= m_Wrapper.m_BattleCommandsActionsCallbackInterface.OnSwitch1;
                @Switch1.canceled -= m_Wrapper.m_BattleCommandsActionsCallbackInterface.OnSwitch1;
                @Switch2.started -= m_Wrapper.m_BattleCommandsActionsCallbackInterface.OnSwitch2;
                @Switch2.performed -= m_Wrapper.m_BattleCommandsActionsCallbackInterface.OnSwitch2;
                @Switch2.canceled -= m_Wrapper.m_BattleCommandsActionsCallbackInterface.OnSwitch2;
                @Switch3.started -= m_Wrapper.m_BattleCommandsActionsCallbackInterface.OnSwitch3;
                @Switch3.performed -= m_Wrapper.m_BattleCommandsActionsCallbackInterface.OnSwitch3;
                @Switch3.canceled -= m_Wrapper.m_BattleCommandsActionsCallbackInterface.OnSwitch3;
                @Switch4.started -= m_Wrapper.m_BattleCommandsActionsCallbackInterface.OnSwitch4;
                @Switch4.performed -= m_Wrapper.m_BattleCommandsActionsCallbackInterface.OnSwitch4;
                @Switch4.canceled -= m_Wrapper.m_BattleCommandsActionsCallbackInterface.OnSwitch4;
                @Switch5.started -= m_Wrapper.m_BattleCommandsActionsCallbackInterface.OnSwitch5;
                @Switch5.performed -= m_Wrapper.m_BattleCommandsActionsCallbackInterface.OnSwitch5;
                @Switch5.canceled -= m_Wrapper.m_BattleCommandsActionsCallbackInterface.OnSwitch5;
                @Switch6.started -= m_Wrapper.m_BattleCommandsActionsCallbackInterface.OnSwitch6;
                @Switch6.performed -= m_Wrapper.m_BattleCommandsActionsCallbackInterface.OnSwitch6;
                @Switch6.canceled -= m_Wrapper.m_BattleCommandsActionsCallbackInterface.OnSwitch6;
            }
            m_Wrapper.m_BattleCommandsActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Move1.started += instance.OnMove1;
                @Move1.performed += instance.OnMove1;
                @Move1.canceled += instance.OnMove1;
                @Move2.started += instance.OnMove2;
                @Move2.performed += instance.OnMove2;
                @Move2.canceled += instance.OnMove2;
                @Move3.started += instance.OnMove3;
                @Move3.performed += instance.OnMove3;
                @Move3.canceled += instance.OnMove3;
                @Move4.started += instance.OnMove4;
                @Move4.performed += instance.OnMove4;
                @Move4.canceled += instance.OnMove4;
                @Switch1.started += instance.OnSwitch1;
                @Switch1.performed += instance.OnSwitch1;
                @Switch1.canceled += instance.OnSwitch1;
                @Switch2.started += instance.OnSwitch2;
                @Switch2.performed += instance.OnSwitch2;
                @Switch2.canceled += instance.OnSwitch2;
                @Switch3.started += instance.OnSwitch3;
                @Switch3.performed += instance.OnSwitch3;
                @Switch3.canceled += instance.OnSwitch3;
                @Switch4.started += instance.OnSwitch4;
                @Switch4.performed += instance.OnSwitch4;
                @Switch4.canceled += instance.OnSwitch4;
                @Switch5.started += instance.OnSwitch5;
                @Switch5.performed += instance.OnSwitch5;
                @Switch5.canceled += instance.OnSwitch5;
                @Switch6.started += instance.OnSwitch6;
                @Switch6.performed += instance.OnSwitch6;
                @Switch6.canceled += instance.OnSwitch6;
            }
        }
    }
    public BattleCommandsActions @BattleCommands => new BattleCommandsActions(this);
    public interface IBattleCommandsActions
    {
        void OnMove1(InputAction.CallbackContext context);
        void OnMove2(InputAction.CallbackContext context);
        void OnMove3(InputAction.CallbackContext context);
        void OnMove4(InputAction.CallbackContext context);
        void OnSwitch1(InputAction.CallbackContext context);
        void OnSwitch2(InputAction.CallbackContext context);
        void OnSwitch3(InputAction.CallbackContext context);
        void OnSwitch4(InputAction.CallbackContext context);
        void OnSwitch5(InputAction.CallbackContext context);
        void OnSwitch6(InputAction.CallbackContext context);
    }
}
